### ISSUE TITLE
Handle exceptions gracefully

### ISSUE THREAD

**Issue by potomak** [ocharles/ekg-carbon#3]
I'd like to use this library without caring about exceptions that could be thrown as result of network errors during the connection or trying to send data to Carbon.

I'd like specifically to change the behavior of the *finally* function used at https://github.com/ocharles/ekg-carbon/blob/c6e5f8d2351d7f5f269dc1f24463b1778246077e/src/System/Remote/Monitoring/Carbon.hs#L94-L97.

The server using this library crashes in two ways:

1. trying to connect to a closed port (`connect: does not exist (Connection refused)`)
1. trying to send data to a closed connection (`writev: resource vanished (Broken pipe)`)

(1) could be avoided by catching exceptions thrown by `forkCarbon`.
(2) could be avoided by catching exceptions in the parent thread.

Note about (2): it could be difficult to debug this error if you're using a warp server, because this kind of exception doesn't generate any error message, see https://github.com/yesodweb/wai/commit/9015db12a3f59765bafd004099c4d4a71b245144#commitcomment-11937357.

Do you have any suggestions?

**Comment by ocharles** [comment]
I've taken a slightly different approach - https://github.com/ocharles/ekg-carbon/commit/d8bb3f38a724b8b13b9852f7dcbd5b972735bcc9. Could you give that a try and see if it meets your needs? I mostly don't want to force opinions on users, such as logging to stderr or restarting by default.

**Comment by potomak** [comment]
@ocharles I tried your version, everything went fine, except for the reconnection. When I close the connection the restart function doesn't retry to connect to Carbon making this approach less effective. What do you think about moving `Carbon.connect (Network.addrAddress addrInfo)` inside `go`?

**Comment by ocharles** [comment]
Ah yea, you're right - that's worth doing. I think it should `disconnect` on exception, and then `go` can reconnect.

**Comment by potomak** [comment]
@ocharles can I help in anyway or you're going to update master?

**Comment by ocharles** [comment]
I'm in the middle of some other work at the moment, will happily accept a
pull request on top of the current master branch :)

**Comment by ocharles** [comment]
Fix released as `ekg-carbon-1.0.4`.

**Comment by ocharles** [comment]
Thanks for all your help, btw! :+1:

**Comment by potomak** [comment]
@ocharles :+1:
