### ISSUE TITLE
Missing \ for lambda in `forkCarbonRestart` Haddocks

### ISSUE THREAD

**Issue by MaxGabriel** [ocharles/ekg-carbon#7]
The current `forkCarbonRestart` docs are missing a backslash to start the exception handler lambda:

``` haskell
forkCarbonRestart opts
                    store
                    (ex restart -> do hPutStrLn stderr ("ekg-carbon: " ++ show ex)
                                       restart)
```

It looks like it's getting treated as Haddock markup and removed. I'm working on a PR to fix

**Comment by ocharles** [comment]
Was fixed with https://github.com/ocharles/ekg-carbon/pull/8
